<div style="color:white;
           display:fill;
           border-radius:5px;
           background-color:#5642C5;
           font-size:200%;
           font-\amily:Arial;letter-spacing:0.5px">

<p width = 20%, style="padding: 10px;
              color:white;">
Object Oriented Programming
              
</p>
</div>

Data Science Cohort Live NYC Aug 2024
<p>Phase 3: Topic 21</p>
<br>
<br>

<div align = "right">
<img src="Images/flatiron-school-logo.png" align = "right" width="200"/>
</div>

#### Objected Oriented Programming

- We've actually been using this without realizing it.


#### Examples

- results object in statsmodels OLS fit
- requests object or BeautifulSoup objects in web scraping
- sklearn LinearRegression models
- fig and ax objects in Matplotlib

#### Object Oriented Program in a Nutshell

<center><img src = "Images/pikachu.png" width = 800 /></center>

- Class: Pokemon
- object instance of Pokemon class

- Attributes = Fields. Properties of object instance.
- Methods: an action. Can change state of object instance.

<center><img src = "Images/pikachu.png" width = 800 /></center>

-  **Class**: general class of similar objects
- Want common attributes/methods for each instantiated object

**Pokemon is general class. Pikachu is an object of class Pokemon.**

<center><img src = "Images/pikachu.png" width = 800 /></center>

**Fields/Attributes**:
- objects of same class share same attributes
- each attribute takes on different values for different instantiations.
    
e.g., Name, Type, Health attributes common to all pokemons


But Pikachu and Bulbasaur:
- different values of attributes.

<center><img src = "Images/pikachu.png" width = 800 /></center>

**Methods**:
- Objects in given Class can execute common set of functions
- Functions can change internal state of object
    - i.e. change attributes: .evolve() can change health, name, etc.

#### Creating a class in Python

Create simple class using class constructor and initialization:

In [1]:
class Pokemon:

    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
        

the __init__ method is a special function:

- the first argument is always: *self*
- *self* refers to specific instance of class. 
- the other arguments: initalization arguments 
    - user specified inputs in initializing instance.
    - can have default arguments


In [2]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
        

#### Let's see this in action 

Create an instance of a Pokemon:
- Create and instantiate a Pikachu.

In [51]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

In [52]:
pikachu

Let's check out some of the attributes

In [53]:
pikachu.attack_power

7

In [5]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points

- So far the class object is like a grouping of variables (like a dict). 
- Adding methods give class objects a richer structure

#### Methods

- Create functions that:
    - return object state
    - update object state (i.e. change internal attributes)
    - do it based on information external to object.


In [6]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
    
    def get_state(self):
        
        state_dict = {'name': self.name, 'level': self.level, 'life': self.life,
                     'attack': self.attack_power, 'defense': self.defense_points}
        return state_dict
        
    def evolve(self, evolved_name):
        #Change Pokemon name to given evolved name state
        self.name = evolved_name
        
        #level up the stats
        self.level += 1
        self.life += 30
        self.attack_power += 4
        self.defense_points += 3

In [54]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

In [55]:
pikachu.get_state()

{'name': 'Pikachu', 'level': 2, 'life': 70, 'attack': 7, 'defense': 4}

<img src = "Images/evolution_phases.jpeg" width = 700 />

In [56]:
pikachu.evolve('Raichu')

In [57]:
pikachu.get_state()

{'name': 'Raichu', 'level': 3, 'life': 100, 'attack': 11, 'defense': 7}

Let's have fun with another class:
- Create a koala class with each instance a koala that eats bunches of eucalyptus and poops.
- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

<center><img src = "Images/gastro.jpg" width = 1000/></center>

Your data science instructor really doesn't get this objected oriented programming stuff! Help him out.

In [11]:
class Koala:
    
    # first need to initialize. 
    #define relevant variables.
    def __init__(self, belly_weight, name, alive = 'Alive'):
        self.weight = belly_weight
        self.name = name
        self.status = alive
    # create eat_eucalyptus() method
    def alive_status(self):
        if self.weight > 6:
            self.status = 'Dead'
        else:
            pass
        return self.status
            
    def eat_eucalyptus(self, num_bunches = 1):
        if self.status == 'Alive':
            self.weight += num_bunches
        else:
            print("Dead koalas dont eat")
        
    # create poop() method
    def poop(self, poop_weight = 0.5):
        if self.status == 'Alive':
            self.weight -= poop_weight
        else:
            print("Dead koalas don't poop.")
    
    
    

In [59]:
koala1 = Koala(2, 'Randy')

In [61]:
koala1.weight

2

In [62]:
koala1.alive_status()

'Alive'

In [63]:
koala1.eat_eucalyptus()

In [64]:
koala1.weight

3

In [65]:
koala1.poop()

In [66]:
koala1.weight

2.5

In [67]:
koala1.alive_status()

'Alive'

In [68]:
koala1.eat_eucalyptus(8)

In [69]:
koala1.alive_status()

'Dead'

In [70]:
koala1.poop()

Dead koalas don't poop.



- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

Now for why all this is relevant to our work in data science.

In [23]:
class Standardizer:
    
    def __init__(self):
        self.mean_series = None
        self.stdev_series = None
    
    def fit(self, data):
        self.mean_series = data.mean()
        self.stdev_series = data.std(ddof = 1)
        
    def transform(self, X):
        X_standard = (X - self.mean_series)/self.stdev_series 
        return X_standard
    
    def fit_transform(self, X):
        #fit with X
        self.fit(X)
        #apply transformation to X
        transformed = self.transform(X)
        return transformed      

In [24]:
import pandas as pd
heart_df = pd.read_csv('Data/heart.csv', usecols = ['age', 'chol', 'thalach', 'target'])
heart_df.head()

age  chol  thalach  target
0   63   233      150       1
1   37   250      187       1
2   41   204      172       1
3   56   236      178       1
4   57   354      163       1

Split into train and test sets.

In [25]:
from sklearn.model_selection import train_test_split
X = heart_df.drop(columns = ['target'])
y = heart_df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

Let's use our standardizer class! 
- Instantiate transformer object.
- Fit our standardizer object to the training set.

In [71]:
sd = Standardizer()
sd

In [72]:
sd.mean_series

In [73]:
sd.stdev_series

Fit the transformer.

In [74]:
sd.fit(X_train)

In [75]:
sd.mean_series

age         54.280992
chol       248.239669
thalach    150.454545
dtype: float64

In [76]:
sd.stdev_series

age         8.961627
chol       53.624254
thalach    22.555602
dtype: float64

Means and standard deviations for each column:
- extracted (fit) from training set.
- use these parameters to transform both train and test

#### Transform train set

In [77]:
X_train_standard = sd.transform(X_train)
X_train_standard.head()

age      chol   thalach
58  -2.263093 -1.235256  1.043885
126 -0.812463 -0.824994 -0.330496
219 -0.700876  0.144717 -0.020152
211  0.749753  0.219310 -0.463501
91   0.303406 -0.769049  0.777876

In [33]:
X_train_standard.info()

<class 'pandas.core.frame.DataFrame'>
Index: 242 entries, 58 to 56
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   age      242 non-null    float64
 1   chol     242 non-null    float64
 2   thalach  242 non-null    float64
dtypes: float64(3)
memory usage: 7.6 KB


In [79]:
X_train_standard.mean()

age       -2.422305e-16
chol      -2.385603e-17
thalach   -5.725448e-16
dtype: float64

#### Transform test set
- Use fitted parameters to transform test set.

In [80]:
X_test_standard = sd.transform(X_test)
X_test_standard.head()

age      chol   thalach
50  -0.366116  0.144717 -0.064487
113 -1.258811 -0.694456  0.467532
129  2.200383  0.387144 -1.305864
202  0.414993  0.405793 -1.749213
187 -0.031355  0.331200 -1.837882

In [82]:
X_test_standard.std()

age        1.072888
chol       0.811428
thalach    1.071539
dtype: float64

Scikit-learn transformers are instances of class objects.

In [83]:
from sklearn.preprocessing import StandardScaler
sklearn_sd = StandardScaler()

X_train_sklearn = sklearn_sd.fit_transform(X_train)

In [84]:
sklearn_sd.mean_

array([ 54.28099174, 248.23966942, 150.45454545])

In [85]:
sklearn_sd.scale_

array([ 8.94309202, 53.51334502, 22.50895139])

Looking at the desciptive statistics of the transformed $X_{train}$:

In [86]:
print(X_train_sklearn.mean(axis = 0))

[-2.27549843e-16 -4.03717464e-17 -5.83555243e-16]


In [87]:
print(X_train_sklearn.std(axis = 0))

[1. 1. 1.]


Yeah, its doing the same thing as our hard-coded class.

#### Models in scikit-learn
- Also classes with different methods.
- .fit()
- .predict()
- .fit_predict()
- .score(X,y)

LinearRegression() was an example.

In [88]:
from numpy import linalg # linear algebra subpackage
import numpy as np

Implementing custom OLS linear regression class:
- sklearn model doing similar things under hood of
    - .fit(X,y) method
    - .predict(X) method
    - etc.

In [43]:
class CustomLinearRegression:
    
    def __init__(self):
        self.intercept = None
        self.coeff = None
        
    def fit(self, X_in, y):
        
        #create a column of 1s for offset fitting
        bias_col = np.ones(X_in.shape[0]).reshape(-1,1) 
    
        #augmented data matrix with column of ones
        X = np.hstack((bias_col, X_in))
        
        # weights: result of least squares minimization
        w = linalg.inv(X.T@X)@(X.T@y)
        # its a formula
        
        self.intercept = w[0]
        self.coeff = w[1::]
        
    # same as y = beta_0 + beta_1*x_1 + beta_2*x_2 + ... + beta_n*x_n
    #just more compact. we'll see later.
    def predict(self, X):
        y_pred = X@self.coeff + self.intercept
        return y_pred
    

Create instances of our custom model and scikit-learn linear regression model

In [44]:
from sklearn.linear_model import LinearRegression
clr = CustomLinearRegression()
sklearn_lr = LinearRegression()

Scikit-learn linear regression .fit() method:
- find weights/model parameters

In [45]:
clr.fit(X_train, y_train)
sklearn_lr.fit(X_train, y_train)

LinearRegression()

In [46]:
clr.coeff

array([-0.00276796, -0.0006423 ,  0.00848256])

In [47]:
sklearn_lr.coef_

array([-0.00276796, -0.0006423 ,  0.00848256])


Under the hood, sklearn model is:

Class object with model parameters as attributes.

- .fit(X,y) method uses formula or algorithm to find model parameters (weights)
- used X, y as training data

- .predict(X) 
    - learned parameters + X into model
    - get prediction

In [48]:
clr.predict(X_test)[0:5]

50     0.549610
113    0.702448
129    0.240086
202    0.198905
187    0.195581
dtype: float64

In [49]:
sklearn_lr.predict(X_test)[0:5]

array([0.54961018, 0.70244788, 0.24008558, 0.19890495, 0.19558083])

We showed:
- Clearly how sklearn works under the hood via class objects   
- But not integrated into the scikit-learn library
    


Next: 
- Learn about parent/child classes
- Inheritance and class hierarchy
- Integrate our models/transformers into scikit-learn class hierarchy.